package views.list;

import controllers.DonGiaPhongBenhCtrl;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.DonGiaPhongBenhModel;
import utils.DialogHelper;
import utils.Validator;

/**
 *
 * @author Phu Bao
 */
public class DSDonGiaPhongBenh extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<DonGiaPhongBenhModel> dsDonGiaPhongBenh = new ArrayList<>();

    public DSDonGiaPhongBenh() {
        initComponents();
        tableModel = (DefaultTableModel) tblDanhSachDonGia.getModel();
        try {
            hienThiDonGiaPhongBenh();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hienThiDonGiaPhongBenh() throws ClassNotFoundException {
        dsDonGiaPhongBenh = DonGiaPhongBenhCtrl.hienThiTatCa();
        tableModel.setRowCount(0);
        dsDonGiaPhongBenh.forEach(dg -> {
            tableModel.addRow(new Object[]{dg.getMaDonGia(), dg.getTenLoaiPhong(), dg.getDonGia()});
        });
    }

    private void hienThiDonGiaPhongBenhTheoDonGia_TangDan() throws ClassNotFoundException {
        dsDonGiaPhongBenh = DonGiaPhongBenhCtrl.sapXepTheoGiaTien_TangDan();
        tableModel.setRowCount(0);
        dsDonGiaPhongBenh.forEach(dg -> {
            tableModel.addRow(new Object[]{dg.getMaDonGia(), dg.getTenLoaiPhong(), dg.getDonGia()});
        });
    }

    private void hienThiDonGiaPhongBenhTheoDonGia_GiamDan() throws ClassNotFoundException {
        dsDonGiaPhongBenh = DonGiaPhongBenhCtrl.sapXepTheoGiaTien_GiamDan();
        tableModel.setRowCount(0);
        dsDonGiaPhongBenh.forEach(dg -> {
            tableModel.addRow(new Object[]{dg.getMaDonGia(), dg.getTenLoaiPhong(), dg.getDonGia()});
        });
    }

    private void hienThiDonGiaPhongBenhTheoTenLoaiPhong_AZ() throws ClassNotFoundException {
        dsDonGiaPhongBenh = DonGiaPhongBenhCtrl.sapXepTheoTenLoaiPhong_AZ();
        tableModel.setRowCount(0);
        dsDonGiaPhongBenh.forEach(dg -> {
            tableModel.addRow(new Object[]{dg.getMaDonGia(), dg.getTenLoaiPhong(), dg.getDonGia()});
        });
    }

    private void hienThiDonGiaPhongBenhTheoTenLoaiPhong_ZA() throws ClassNotFoundException {
        dsDonGiaPhongBenh = DonGiaPhongBenhCtrl.sapXepTheoTenLoaiPhong_ZA();
        tableModel.setRowCount(0);
        dsDonGiaPhongBenh.forEach(dg -> {
            tableModel.addRow(new Object[]{dg.getMaDonGia(), dg.getTenLoaiPhong(), dg.getDonGia()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachDonGia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaDonGia = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtTenLoaiPhong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXuatDanhSach = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboSapXep = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ĐƠN GIÁ PHÒNG BỆNH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblDanhSachDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhSachDonGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Đơn Giá", "Tên Loại Phòng", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachDonGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachDonGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachDonGia);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã đơn giá");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Đơn giá");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên loại phòng");

        txtMaDonGia.setEditable(false);
        txtMaDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDonGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDonGiaFocusLost(evt);
            }
        });

        txtTenLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnThem.setBackground(new java.awt.Color(0, 102, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(0, 102, 255));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 102, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXuatDanhSach.setBackground(new java.awt.Color(0, 102, 255));
        btnXuatDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatDanhSach.setText("Xuất danh sách");
        btnXuatDanhSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("DANH SÁCH ĐƠN GIÁ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sắp xếp");

        cboSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định", "Sắp xếp theo Đơn giá: Tăng dần", "Sắp xếp theo Đơn giá: Giảm dần", "Sắp xếp theo Tên loại phòng: A - Z", "Sắp xếp theo Tên loại phòng: Z - A" }));
        cboSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDonGia)
                            .addComponent(txtTenLoaiPhong)
                            .addComponent(txtMaDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXuatDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXuatDanhSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        try {
            int selectedIndex = tblDanhSachDonGia.getSelectedRow();
            if (selectedIndex >= 0) {
                String maDonGia = txtMaDonGia.getText();
                String tenLoaiPhong = txtTenLoaiPhong.getText();
                String donGiaStr = txtDonGia.getText();
                if (tenLoaiPhong.isEmpty() || donGiaStr.isEmpty()) {
                    DialogHelper.showError("Vui lòng điền đầy đủ các thông tin");
                } else if (!Validator.isIntegerString(donGiaStr)) {
                    DialogHelper.showError("Đơn giá không hợp lệ");
                }else {
                    int donGia = Integer.parseInt(donGiaStr);
                    DonGiaPhongBenhModel dg = new DonGiaPhongBenhModel(maDonGia, tenLoaiPhong, donGia);
                    try {
                        DonGiaPhongBenhCtrl.capNhatLoaiPhong(dg);
                        DialogHelper.showMessage("Cập nhật thành công");
                        hienThiDonGiaPhongBenh();
                        lamMoi();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (ClassCastException ex) {
            Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtDonGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonGiaFocusLost
        // TODO add your handling code here:
        String donGia = txtDonGia.getText();
        if (!donGia.isEmpty() && !Validator.isIntegerString(donGia)) {
            DialogHelper.showError("Đơn giá phòng không hợp lệ");
            txtDonGia.requestFocus();
        }
    }//GEN-LAST:event_txtDonGiaFocusLost

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            String maDonGia = txtMaDonGia.getText();
            if (!maDonGia.isEmpty()) {
                DialogHelper.showError("Loại phòng đã tồn tại trong cơ sở dữ liệu");
            } else {
                String tenLoaiPhong = txtTenLoaiPhong.getText();
                String donGiaStr = txtDonGia.getText();

                if (tenLoaiPhong.isEmpty() || donGiaStr.isEmpty()) {
                    DialogHelper.showError("Vui lòng điền đầy đủ các thông tin");
                } else if (!Validator.isIntegerString(donGiaStr)) {
                    DialogHelper.showError("Đơn giá không hợp lệ");
                } else {
                    int donGia = Integer.parseInt(donGiaStr);
                    DonGiaPhongBenhModel dg = new DonGiaPhongBenhModel(maDonGia, tenLoaiPhong, donGia);
                    try {
                        DonGiaPhongBenhCtrl.themLoaiPhongBenh(dg);
                        DialogHelper.showMessage("Thêm thành công");
                        hienThiDonGiaPhongBenh();
                        lamMoi();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (ClassCastException ex) {
            Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void lamMoi() {
        txtMaDonGia.setText("");
        txtTenLoaiPhong.setText("");
        txtDonGia.setText("");
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
        cboSapXep.setSelectedIndex(0);
        try {
            hienThiDonGiaPhongBenh();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblDanhSachDonGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachDonGiaMouseClicked
        // TODO add your handling code here:
        lamMoi();
        int selectedIndex = tblDanhSachDonGia.getSelectedRow();
        if (selectedIndex >= 0) {
            DonGiaPhongBenhModel dg = dsDonGiaPhongBenh.get(selectedIndex);
            txtMaDonGia.setText(dg.getMaDonGia());
            txtTenLoaiPhong.setText(dg.getTenLoaiPhong());
            int donGiaValue = dg.getDonGia();
            txtDonGia.setText(String.valueOf(donGiaValue));
        } else {
            System.out.println("Chưa có dòng nào được chọn");
        }
    }//GEN-LAST:event_tblDanhSachDonGiaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblDanhSachDonGia.getSelectedRow();
        if (selectedIndex >= 0) {
            DonGiaPhongBenhModel dg = dsDonGiaPhongBenh.get(selectedIndex);

            boolean option = DialogHelper.showConfirmation("Bạn có chắc muốn xóa Loại phòng này không?");

            if (option) {
                try {
                    DonGiaPhongBenhCtrl.xoaLoaiPhong(dg);
                    DialogHelper.showMessage("Xóa thành công");
                    hienThiDonGiaPhongBenh();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            DialogHelper.showError("Chưa chọn dòng nào trong Table");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cboSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSapXepActionPerformed
        // TODO add your handling code here:
        switch (cboSapXep.getSelectedIndex()) {
            case 0 -> {
                try {
                    hienThiDonGiaPhongBenh();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 1 -> {
                try {
                    hienThiDonGiaPhongBenhTheoDonGia_TangDan();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 2 -> {
                try {
                    hienThiDonGiaPhongBenhTheoDonGia_GiamDan();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 3 -> {
                try {
                    hienThiDonGiaPhongBenhTheoTenLoaiPhong_AZ();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 4 -> {
                try {
                    hienThiDonGiaPhongBenhTheoTenLoaiPhong_ZA();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            default -> {
                try {
                    hienThiDonGiaPhongBenh();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_cboSapXepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSDonGiaPhongBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSDonGiaPhongBenh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatDanhSach;
    private javax.swing.JComboBox<String> cboSapXep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSachDonGia;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDonGia;
    private javax.swing.JTextField txtTenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
