package views.list;

import controllers.QuanLyCtrl;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import models.QuanLyModel;
import utils.DialogHelper;
import utils.Validator;

/**
 *
 * @author Phu Bao
 */
public class DSQuanLy extends javax.swing.JPanel {

    /**
     * Creates new form DSQuanLy
     */
    DefaultTableModel tableModel;
    List<QuanLyModel> dsQuanLy = new ArrayList<>();
    private String currentImage;
    private String defaultPath = "src/main/java/Images/QuanLy/default.png";

    public DSQuanLy() {
        this.currentImage = defaultPath;
        initComponents();
        tableModel = (DefaultTableModel) tblDanhSachQuanLy.getModel();
        try {
            hienThiTatCaQuanLy();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hienThiTatCaQuanLy() throws ClassNotFoundException {
        dsQuanLy = QuanLyCtrl.hienThiTatCa();
        tableModel.setRowCount(0);
        dsQuanLy.forEach(ql -> {
            tableModel.addRow(new Object[]{ql.getMaQuanLy(), ql.getHoTen(),
                ql.getGioiTinh(), ql.getEmail(), ql.getCanCuoc(), ql.getSoDienThoai(),
                ql.getDiaChi(), ql.getNamSinh()});
        });
    }

    private void hienThiTatCaQuanLyTheoTen_AZ() throws ClassNotFoundException {
        dsQuanLy = QuanLyCtrl.sapXepTheoTen_AZ();
        tableModel.setRowCount(0);
        dsQuanLy.forEach(ql -> {
            tableModel.addRow(new Object[]{ql.getMaQuanLy(), ql.getHoTen(),
                ql.getGioiTinh(), ql.getEmail(), ql.getCanCuoc(), ql.getSoDienThoai(),
                ql.getDiaChi(), ql.getNamSinh()});
        });
    }

    private void hienThiTatCaQuanLyTheoTen_ZA() throws ClassNotFoundException {
        dsQuanLy = QuanLyCtrl.sapXepTheoTen_ZA();
        tableModel.setRowCount(0);
        dsQuanLy.forEach(ql -> {
            tableModel.addRow(new Object[]{ql.getMaQuanLy(), ql.getHoTen(),
                ql.getGioiTinh(), ql.getEmail(), ql.getCanCuoc(), ql.getSoDienThoai(),
                ql.getDiaChi(), ql.getNamSinh()});
        });
    }

    private void hienThiTatCaQuanLyTheoNamSinh_TangDan() throws ClassNotFoundException {
        dsQuanLy = QuanLyCtrl.sapXepTheoNamSinh_TangDan();
        tableModel.setRowCount(0);
        dsQuanLy.forEach(ql -> {
            tableModel.addRow(new Object[]{ql.getMaQuanLy(), ql.getHoTen(),
                ql.getGioiTinh(), ql.getEmail(), ql.getCanCuoc(), ql.getSoDienThoai(),
                ql.getDiaChi(), ql.getNamSinh()});
        });
    }

    private void hienThiTatCaQuanLyTheoNamSinh_GiamDan() throws ClassNotFoundException {
        dsQuanLy = QuanLyCtrl.sapXepTheoNamSinh_GiamDan();
        tableModel.setRowCount(0);
        dsQuanLy.forEach(ql -> {
            tableModel.addRow(new Object[]{ql.getMaQuanLy(), ql.getHoTen(),
                ql.getGioiTinh(), ql.getEmail(), ql.getCanCuoc(), ql.getSoDienThoai(),
                ql.getDiaChi(), ql.getNamSinh()});
        });
    }

    private void hienThiDanhSachQuanLyTimKiem(String tuKhoa) throws ClassNotFoundException {
        dsQuanLy = QuanLyCtrl.timKiemQuanLy(tuKhoa);
        tableModel.setRowCount(0);
        dsQuanLy.forEach(ql -> {
            tableModel.addRow(new Object[]{ql.getMaQuanLy(), ql.getHoTen(),
                ql.getGioiTinh(), ql.getEmail(), ql.getCanCuoc(), ql.getSoDienThoai(),
                ql.getDiaChi(), ql.getNamSinh()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnXuatDanhSach = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoaQuanLy = new javax.swing.JButton();
        btnThemQuanLy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaQuanLy = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboSapXep = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachQuanLy = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        txtNamSinh = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCanCuoc = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 660));

        jPanel4.setPreferredSize(new java.awt.Dimension(88, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("THÔNG TIN QUẢN LÝ");

        btnXuatDanhSach.setBackground(new java.awt.Color(0, 102, 255));
        btnXuatDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatDanhSach.setText("Xuất danh sách");
        btnXuatDanhSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXuatDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatDanhSach.setPreferredSize(new java.awt.Dimension(120, 25));
        btnXuatDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDanhSachActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(80, 25));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(0, 102, 255));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.setPreferredSize(new java.awt.Dimension(120, 25));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoaQuanLy.setBackground(new java.awt.Color(0, 102, 255));
        btnXoaQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaQuanLy.setText("Xóa quản lý");
        btnXoaQuanLy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoaQuanLy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaQuanLy.setPreferredSize(new java.awt.Dimension(120, 25));
        btnXoaQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaQuanLyActionPerformed(evt);
            }
        });

        btnThemQuanLy.setBackground(new java.awt.Color(0, 102, 255));
        btnThemQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btnThemQuanLy.setText("Thêm quản lý");
        btnThemQuanLy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThemQuanLy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemQuanLy.setPreferredSize(new java.awt.Dimension(130, 25));
        btnThemQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemQuanLyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnXoaQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnXuatDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnXuatDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã quản lý");

        txtMaQuanLy.setEditable(false);
        txtMaQuanLy.setBackground(new java.awt.Color(204, 204, 204));
        txtMaQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Họ tên");

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Email");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Điện thoại");

        txtDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Địa chỉ");

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel8.setPreferredSize(new java.awt.Dimension(199, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("DANH SÁCH QUẢN LÝ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tìm kiếm");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Sắp xếp");

        cboSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định", "Họ tên : A - Z", "Họ tên : Z - A", "Năm sinh : Tăng dần", "Năm sinh : Giảm dần " }));
        cboSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tblDanhSachQuanLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã quản lý", "Họ tên", "Giới tính", "Email", "Căn cước", "Số điện thoại", "Địa chỉ", "Năm sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachQuanLyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachQuanLy);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Giới tính");

        cboGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Năm sinh");

        lblImage.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Hình ảnh");
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ảnh thẻ");

        btnChonAnh.setBackground(new java.awt.Color(204, 204, 204));
        btnChonAnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChonAnh.setText("Chọn file");
        btnChonAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        txtNamSinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Căn cước");

        txtCanCuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(34, 34, 34)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel2)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(txtCanCuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(58, 58, 58)
                        .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnChonAnh))
                        .addGap(18, 18, 18)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtMaQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCanCuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDanhSachActionPerformed

    }//GEN-LAST:event_btnXuatDanhSachActionPerformed

    private void lamMoi() {
        txtMaQuanLy.setText("");
        txtHoTen.setText("");
        cboGioiTinh.setSelectedIndex(0);
        txtDiaChi.setText("");
        txtNamSinh.setText("");
        txtCanCuoc.setText("");
        txtDienThoai.setText("");
        txtEmail.setText("");
        currentImage = defaultPath;
        showImageOnLabel(currentImage);
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoi();
        try {
            hienThiTatCaQuanLy();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            int selectedIndex = tblDanhSachQuanLy.getSelectedRow();
            if (selectedIndex >= 0) {
                String maQuanLy = txtMaQuanLy.getText();
                String hoTen = txtHoTen.getText();
                String gioiTinh = cboGioiTinh.getSelectedItem().toString();
                String diaChi = txtDiaChi.getText();
                String namSinh = txtNamSinh.getText();
                String canCuoc = txtCanCuoc.getText();
                String soDienThoai = txtDienThoai.getText();
                String email = txtEmail.getText();

                if (hoTen.isEmpty() || email.isEmpty() || namSinh.isEmpty() || canCuoc.isEmpty()) {
                    DialogHelper.showError("Vui lòng điền đầy đủ thông tin");
                } else if (!namSinh.isEmpty() && !Validator.isValidYearOfBirth(namSinh)) {
                    DialogHelper.showError("Năm sinh không hợp lệ");
                } else if (!email.isEmpty() && !Validator.isValidEmail(email)) {
                    DialogHelper.showError("Email không hợp lệ");
                } else if (!soDienThoai.isEmpty() && !Validator.isValidPhoneNumber(soDienThoai)) {
                    DialogHelper.showError("Số điện thoại không hợp lệ");
                } else if (!canCuoc.isEmpty() && !Validator.isValidCccd(canCuoc)) {
                    DialogHelper.showError("Căn cước không hợp lệ");
                } else if (!canCuoc.isEmpty() && QuanLyCtrl.kiemTraCanCuocCoTonTai_CapNhat(canCuoc, maQuanLy)) {
                    DialogHelper.showError("Căn cước đã tồn tại");
                } else {
                    QuanLyModel ql = new QuanLyModel(maQuanLy, email, hoTen, gioiTinh, diaChi, namSinh, soDienThoai, canCuoc, currentImage);
                    QuanLyCtrl.capNhatQuanLy(ql);
                    DialogHelper.showMessage("Cập nhật thành công.");
                    hienThiTatCaQuanLy();
                    lamMoi();
                }
            } else {
                DialogHelper.showError("Chưa có dòng nào trong bảng được chọn");
            }
        } catch (ClassCastException | ClassNotFoundException ex) {
            Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaQuanLyActionPerformed
        int selectedIndex = tblDanhSachQuanLy.getSelectedRow();
        if (selectedIndex >= 0) {
            QuanLyModel ql = dsQuanLy.get(selectedIndex);
            boolean option = DialogHelper.showConfirmation("Bạn có chắc muốn xóa Quản lý này không?");
            if (option) {
                try {
                    QuanLyCtrl.xoaQuanLy(ql);
                    DialogHelper.showMessage("Xóa thành công");
                    hienThiTatCaQuanLy();
                    lamMoi();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            DialogHelper.showError("Chưa có Quản lý nào được chọn.");
        }
    }//GEN-LAST:event_btnXoaQuanLyActionPerformed

    private void btnThemQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemQuanLyActionPerformed
        if (!txtMaQuanLy.getText().isEmpty()) {
            DialogHelper.showError("Quản lý đã tồn tại");
        } else {
            try {
                String hoTen = txtHoTen.getText();
                String gioiTinh = cboGioiTinh.getSelectedItem().toString();
                String diaChi = txtDiaChi.getText();
                String sdt = txtDienThoai.getText();
                String namSinh = txtNamSinh.getText();
                String canCuoc = txtCanCuoc.getText();
                if (hoTen.isEmpty() || namSinh.isEmpty() || canCuoc.isEmpty()) {
                    DialogHelper.showError("Vui lòng điền đầy đủ thông tin");
                } else if (!namSinh.isEmpty() && !Validator.isValidYearOfBirth(namSinh)) {
                    DialogHelper.showError("Năm sinh không hợp lệ");
                } else if (QuanLyCtrl.kiemTraCanCuocCoTonTai(canCuoc)) {
                    DialogHelper.showError("Căn cước đã tồn tại");
                } else if (!sdt.isEmpty() && !Validator.isValidPhoneNumber(sdt)) {
                    DialogHelper.showError("Số điện thoại không hợp lệ");
                } else if (!canCuoc.isEmpty() && !Validator.isValidCccd(canCuoc)) {
                    DialogHelper.showError("Căn cước không hợp lệ");
                } else {
                    QuanLyModel ql = new QuanLyModel(hoTen, gioiTinh, diaChi, namSinh, sdt, canCuoc, currentImage);
                    QuanLyCtrl.themQuanLy(ql);
                    hienThiTatCaQuanLy();
                    DialogHelper.showMessage("Thêm thành công!");
                    lamMoi();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemQuanLyActionPerformed

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        // TODO add your handling code here:
        String tuKhoa = txtTimKiem.getText();
        try {
            hienThiDanhSachQuanLyTimKiem(tuKhoa);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiemKeyTyped

    private void cboSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSapXepActionPerformed
        // TODO add your handling code here:
        switch (cboSapXep.getSelectedIndex()) {
            case 0 -> {
                try {
                    hienThiTatCaQuanLy();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 1 -> {
                try {
                    hienThiTatCaQuanLyTheoTen_AZ();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 2 -> {
                try {
                    hienThiTatCaQuanLyTheoTen_ZA();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 3 -> {
                try {
                    hienThiTatCaQuanLyTheoNamSinh_TangDan();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case 4 -> {
                try {
                    hienThiTatCaQuanLyTheoNamSinh_GiamDan();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DSQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            default -> {
            }
        }
    }//GEN-LAST:event_cboSapXepActionPerformed

    private void showImageOnLabel(String duongDan) {
        try {
            // Đọc ảnh từ đường dẫn tương đối
            ImageIcon originalIcon = new ImageIcon(ImageIO.read(new File(duongDan)));

            // Lấy kích thước của JLabel
            int labelWidth = lblImage.getWidth();
            int labelHeight = lblImage.getHeight();

            // Chỉnh kích thước của ảnh để phù hợp với JLabel
            Image scaledImage = originalIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

            // Tạo ImageIcon mới từ ảnh đã được chỉnh kích thước
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            // Đặt ảnh cho JLabel
            lblImage.setIcon(scaledIcon);
        } catch (IOException e) {
            DialogHelper.showError("Lỗi hình ảnh: " + e.getMessage());
        }

    }

    private void tblDanhSachQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachQuanLyMouseClicked
        lamMoi();
        int selectedIndex = tblDanhSachQuanLy.getSelectedRow();
        if (selectedIndex >= 0) {
            QuanLyModel ql = dsQuanLy.get(selectedIndex);
            txtMaQuanLy.setText(ql.getMaQuanLy());
            txtHoTen.setText(ql.getHoTen());
            txtDiaChi.setText(ql.getDiaChi());
            txtNamSinh.setText(ql.getNamSinh());
            txtCanCuoc.setText(ql.getCanCuoc());
            txtDienThoai.setText(ql.getSoDienThoai());
            txtEmail.setText(ql.getEmail());
            cboGioiTinh.setSelectedItem(ql.getGioiTinh());
            currentImage = ql.getAnh();
            showImageOnLabel(currentImage);

        } else {
            System.out.println("Chưa có dòng nào được chọn");
        }
    }//GEN-LAST:event_tblDanhSachQuanLyMouseClicked

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        String sourceDirectory = Paths.get("src", "main", "java", "Images", "QuanLy").toAbsolutePath().toString();

        JFileChooser fileChooser = new JFileChooser(sourceDirectory);

        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Hình ảnh", "jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "Chọn File");
        if (x == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                // Đọc ảnh từ đường dẫn
                BufferedImage originalImage = ImageIO.read(selectedFile);

                // Lấy kích thước của JLabel
                int labelWidth = lblImage.getWidth();
                int labelHeight = lblImage.getHeight();

                // Chỉnh kích thước của ảnh để phù hợp với JLabel
                Image scaledImage = originalImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

                // Tạo BufferedImage từ ảnh đã được chỉnh kích thước
                BufferedImage bufferedScaledImage = new BufferedImage(labelWidth, labelHeight, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = bufferedScaledImage.createGraphics();
                g2d.drawImage(scaledImage, 0, 0, null);
                g2d.dispose();

                // Đặt ảnh cho JLabel
                lblImage.setIcon(new ImageIcon(bufferedScaledImage));

                // Tạo chuỗi id duy nhất
                String uniqueID = UUID.randomUUID().toString();

                // Lưu ảnh vào thư mục đích với tên duy nhất
                String newFileName = uniqueID + "_" + selectedFile.getName();
                String relativeImagePath = "src/main/java/Images/QuanLy/" + newFileName;
                File outputfile = new File(relativeImagePath);
                ImageIO.write(bufferedScaledImage, "png", outputfile);

                // Lưu đường dẫn tương đối của ảnh
                currentImage = relativeImagePath;
            } catch (IOException e) {
                e.printStackTrace();
                DialogHelper.showError("Lỗi hình ảnh");
            }
        }
    }//GEN-LAST:event_btnChonAnhActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemQuanLy;
    private javax.swing.JButton btnXoaQuanLy;
    private javax.swing.JButton btnXuatDanhSach;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboSapXep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblDanhSachQuanLy;
    private javax.swing.JTextField txtCanCuoc;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaQuanLy;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
